image_size: 150
latent_dim: 128
image_dim:  ${eval: "3 * ${model.image_size} * ${model.image_size}"}

image_mean: [0.485, 0.456, 0.406]
image_std: [0.229, 0.224, 0.225]

epochs: 20
batch_size: 16

# for saving models
# model_local_path: ../models
# save_top_k: 5
# every_n_epochs: 1